import "./globals.css";

import Navbar from "./components/navbar";
import Footer from "./components/footer";

export const metadata = {
  title: "311-Data Neighborhood Engagement Tool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex h-screen flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
